apiVersion: v1
kind: Pod
metadata:
  name: webapp-sar
  namespace: webapp-namespace
  labels:
    app: employees  
spec:
  containers:
  - name: webapp
    image: 064686496891.dkr.ecr.us-east-1.amazonaws.com/my-app-image:latest
    env:
    - name: DBHOST
      value: "my-mysql-container.mysql-namespace.svc.cluster.local"  
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: "root"
    - name: DBPWD
      value: "password"
    ports:
    - containerPort: 8080
  imagePullSecrets:
  - name: ecr-registry-secret  
 
