apiVersion: v1
kind: Pod
metadata:
  name: mysql-sar
  namespace: mysql-namespace  # Add this line to specify the namespace
  labels:
    app: mysql-sar
spec:
  containers:
  - name: mysql
    image: 064686496891.dkr.ecr.us-east-1.amazonaws.com/my-sql-image:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
    ports:
    - containerPort: 3306
