apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: webapp-namespace
spec:
  selector:
    app: employees  
  ports:
  - protocol: TCP
    port: 80  
    targetPort: 80
    nodePort: 30001
  type: NodePort
