apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: webapp-namespace
  labels:
    app: employees  
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: employees  
  template:
    metadata:
      labels:
        app: employees  
    spec:
      containers:
      - name: webapp
        image: 064686496891.dkr.ecr.us-east-1.amazonaws.com/my-app-image:latest
        env:
        - name: DBHOST
          value: "my-mysql-container.mysql-namespace.svc.cluster.local" 
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "password"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ecr-registry-secret  
